### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by XJtsinghua1992** [KazMorita/polyhedron_distortion#1]
Hi Kazuki Morita,

I found your recent work "[Breaking the Aristotype: Featurization of Polyhedral Distortions in Perovskite Crystals | Chemistry of Materials (acs.org)](https://pubs.acs.org/doi/full/10.1021/acs.chemmater.1c02959)" is very interesting. We would like to use your developed code to perform octahedral distortion analysis. 

But I meet a warning in some POSCARs, while others not. I attach a "good" POSCAR-1 and a "bad" POSCAR-2.
![image](https://github.com/KazMorita/polyhedron_distortion/assets/122658010/1a18eff0-2ebc-44fd-87fa-07d438f070bc)

Could you kindly help check this issue? Thank you very much!

**Comment by KazMorita** [comment]
Hi, 

I can't see the attachment.
[It seems that GitHub only supports certain extensions](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files), so can you add .txt after your POSCAR files and reupload it?

**Comment by XJtsinghua1992** [comment]
Hi Kazuki Morita,

please find POSCAR1 and POSCAR2 in txt.
[POSCAR-1.txt](https://github.com/KazMorita/polyhedron_distortion/files/12594440/POSCAR-1.txt)
[POSCAR-2.txt](https://github.com/KazMorita/polyhedron_distortion/files/12594446/POSCAR-2.txt)

Thank you

**Comment by XJtsinghua1992** [comment]
> Hi,
> 
> I can't see the attachment. [It seems that GitHub only supports certain extensions](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files), so can you add .txt after your POSCAR files and reupload it?

Hi Kazuki Morita,
I have uploaded two txt files in the last dialog. Please let me know if you cannot see them.
Thank you very much

**Comment by KazMorita** [comment]
Apologies for the late response. I reproduced your error.
The error came from CrystalNN in the script not detecting the bonding. I edited it to be more general.
https://github.com/KazMorita/polyhedron_distortion/blob/3891d6aaaa0c6953c789fe614243c6a9c075f3fc/polyhedron_analysis.py#L108-L117
Could you test if the updated script works?
If your structure distorts significantly, you might face a similiar issue. In that case, try adjusting the CrystallNN parameters.

**Comment by KazMorita** [comment]
I will close this issue.
Resolved in commit: 3891d6a

**Comment by XJtsinghua1992** [comment]
Hi Kazuki Morita,
I used your newly developed polyhedron_distortion/polyhedron_analysis.py and found that some structures work well. However, some structures still show the same warning after adjusting the CrystallNN parameter. Can you help to check this?

I attach the POSCAR here. "python polyhedron_analysis_jian.py POSCAR-wrong 84"
[POSCAR-wrong.txt](https://github.com/KazMorita/polyhedron_distortion/files/13371379/POSCAR-wrong.txt)
